version: 0.2

environment_variables:
  plaintext:
    HUGO_VERSION: "0.86.0"
    
phases:
  install:
    commands:
      - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
      - tar -xzf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
      - mv hugo /usr/bin
      - rm -rf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
  build:
    commands:
      - rm -rf public
      - ls themes
      - hugo
      - ls public
  post_build:
    commands:
      - aws s3 sync --delete public s3://hugo-screencast
      - echo Build completed on `date`